name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish images
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hyr326/openvpn-ldap
        tags: "latest"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
